import{a as w,S as P,i as y}from"./assets/vendor-CrAdtshy.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const S="48880683-c6af76fdc924f93949198cfc6",v="https://pixabay.com/api/";async function h(e,r,n){try{return(await w.get(v,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}catch(a){throw console.error("Error fetching images:",a),a}}const x=document.querySelector(".gallery");let I=new P(".gallery a",{});function b(e){const r=e.map(({webformatURL:n,largeImageURL:a,tags:t,likes:o,views:l,comments:E,downloads:L})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img class="gallery-image" src="${n}" alt="${t}" loading="lazy">
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${l}</p>
          <p><b>Comments:</b> ${E}</p>
          <p><b>Downloads:</b> ${L}</p>
        </div>
      </li>
    `).join("");x.insertAdjacentHTML("beforeend",r),I.refresh()}function $(){const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0}const q=document.getElementById("search-form"),p=document.querySelector(".gallery"),s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more");p.after(s);const f=document.getElementById("loader"),m=document.getElementById("loading-text"),d=document.createElement("p");d.textContent="We're sorry, but you've reached the end of search results.";d.style.display="none";p.after(d);let g="",i=1;const c=40;let u=0;s.style.display="none";q.addEventListener("submit",B);s.addEventListener("click",k);async function B(e){if(e.preventDefault(),g=e.target.elements.searchQuery.value.trim(),i=1,u=0,d.style.display="none",!g){y.error({title:"Error",message:"Please enter a search query."});return}p.innerHTML="",s.style.display="none",f.style.display="block",m.style.display="block";try{const r=await h(g,i,c);u=r.totalHits,r.hits.length===0?y.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(b(r.hits),r.hits.length===c&&u>c&&(s.style.display="block"))}catch(r){console.error("Error fetching images:",r),y.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{f.style.display="none",m.style.display="none",e.target.reset()}}async function k(){i++,s.style.display="none",f.style.display="block",m.style.display="block";try{const e=await h(g,i,c);e.hits.length===0||(i-1)*c+e.hits.length===u?(s.style.display="none",d.style.display="block"):(b(e.hits),s.style.display="block");const r=$();window.scrollBy({top:r*2,left:0,behavior:"smooth"})}catch(e){console.error("Error fetching images:",e),y.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{f.style.display="none",m.style.display="none"}}
//# sourceMappingURL=index.js.map
